name: horizontal_card_pager
description: Use dynamic and beautiful card view pagers (horizontal direction) to help you create great apps.
version: 0.2.0
homepage: https://github.com/Origogi/Horizontal_Card_Pager

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.origogi.horizontal_card_pager
        pluginClass: HorizontalCardPagerPlugin
      ios:
        pluginClass: HorizontalCardPagerPlugin

