name: horizontal_card_pager_example
description: Demonstrates how to use the horizontal_card_pager plugin.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  horizontal_card_pager:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets: 
    - images/
    - images/poppy/

  fonts:
    - family: "Bevan"
      fonts:
        - asset: fonts/Bevan-Regular.ttf
    - family: "lol"
      fonts:
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Friz Quadrata Std Italic.otf
          style: italic
